definitions:
  apperrors.DeliveryError:
    properties:
      description:
        type: string
      error:
        type: string
    type: object
  dna.DnaReportStats:
    properties:
      count_human_dna:
        type: integer
      count_mutant_dna:
        type: integer
      ratio:
        type: number
    type: object
  models.IsMutantReqBody:
    properties:
      dna:
        items:
          type: string
        type: array
    required:
    - dna
    type: object
info:
  contact: {}
paths:
  /mutant:
    post:
      consumes:
      - application/json
      description: return true or false by dna input
      parameters:
      - description: dna data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.IsMutantReqBody'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/apperrors.DeliveryError'
      summary: Check if given dna is from a mutant
  /stats:
    get:
      consumes:
      - application/json
      description: return db stats about dna
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dna.DnaReportStats'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperrors.DeliveryError'
      summary: returns db stats about dna
swagger: "2.0"
